### ISSUE TITLE
Remover el botón "Únete a la comunidad"

### ISSUE THREAD

**Issue by JuanVqz** [oaxacarb/oaxacarb.github.io#16]
<img width="1244" alt="Screenshot 2023-10-01 at 19 09 09" src="https://github.com/oaxacarb/oaxacarb.github.io/assets/7331511/99e4aab3-fbb1-4ec1-8975-e5c8b101ac30">

**Comment by agusvama** [comment]
🤔 que tiene de malo?

**Comment by JuanVqz** [comment]
Es un ejemplo para la próxima charla que es relacionada al Hacktoberfest, te esperamos!
