### ISSUE TITLE
[deployment] Usar vercel como herramienta de despliegue

### ISSUE THREAD

**Issue by JuanVqz** [oaxacarb/oaxacarb.github.io#5]
AC:

- Debemos de ser capaces de deployar el blog (en middleman) usando vercel

Links relacionados:
- https://vercel.com/guides/deploying-middleman-with-vercel

**Comment by JuanVqz** [comment]
Vercel no es gratis para organizaciones, asi que usaremos GitHub Pages, o cual era la forma de deployar, alguien recuerda?

**Comment by lesm** [comment]
> Vercel no es gratis para organizaciones, asi que usaremos GitHub Pages, o cual era la forma de deployar, alguien recuerda?

Usamos middleman para el[ deploy aquí el post ](http://oaxacarb.org/posts/como-subir-un-post.html)

**Comment by JuanVqz** [comment]
> 

Genial, cerrando como resuelto!
