### ISSUE TITLE
[chore] Put oaxacarb.org site under https

### ISSUE THREAD

**Issue by lesm** [oaxacarb/oaxacarb.github.io#9]
It looks ugly without https

![Image](https://user-images.githubusercontent.com/7545843/205422965-3e85df80-877f-4900-af98-9d057d5971f9.png)

**Comment by JuanVqz** [comment]
@lesm, How do we achieve it?

**Comment by thotmx** [comment]
Please @JuanVqz assign this to me. I can set this up.

**Comment by thotmx** [comment]
This is done. Please, just confirm it.

**Comment by JuanVqz** [comment]
![image](https://user-images.githubusercontent.com/7331511/205475997-bd65b336-5837-45d7-978f-c30c71a3299f.png)
